name: Semver, Build, Publish

on:
  push:
    branches: [main, alpha, beta]

permissions:
  deployments: write
  issues: write
  pull-requests: write

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release - prepare
        run: |
          cat <<EOF > package.json
          {
            "name": "semver",
            "private": true
          }
          EOF
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/changelog@6.0.2
            @google/semantic-release-replace-plugin@1.2.0
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: semantic
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_channel: ${{ steps.semantic.outputs.new_release_channel }}

  build_and_publish:
    runs-on: ubuntu-latest
    needs: [semver]
    if: needs.semver.outputs.new_release_published == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: install poetry
        uses: abatilo/actions-poetry@v2.2.0

      - name: Build
        run: |
          poetry version ${{ needs.semver.outputs.version }}
          poetry build

      - name: Publish distribution ðŸ“¦ to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
